### ISSUE TITLE
Replace audio error

### ISSUE THREAD

**Issue by howlunit** [master131/Black-Ops-II-Sound-Studio#1]
When i replace an audio file from a .sabs "pack file" and try to save the .sabs file, an error happens.
"Object reference not set to an instance of an object."
I can't save an .sabs file whit some changed audios.

**Comment by master131** [comment]
Apologies, can you try the attached build and see if that fixes the issue (also maybe test with the game as well):

**Comment by howlunit** [comment]
Oh that version solved it. Thanks Master.

**Comment by master131** [comment]
No problems, thanks for raising the issue.
