### ISSUE TITLE
Is this project still being worked on?

### ISSUE THREAD

**Issue by GillMart** [master131/Black-Ops-II-Sound-Studio#8]
First of all, thank you so much for making this. This is practically the only reason the mod I've been working on for BO2 Plutonium is able to exist. My team and I are still in the midst of modding BO2 but are also planning on expanding to BO3 afterward. Problem is, there is seemingly no application of this kind for BO3. When I noticed this hasn't been updated since November of 2020 I feared the worst. Are my suspicions true, or are you planning on continuing? Thanks!

**Comment by master131** [comment]
There is no active work planned on this application - what exactly is the issue?

**Comment by GillMart** [comment]
> There is no active work planned on this application - what exactly is the issue?

Sorry for the confusion. I was inquiring about support for saving SABS/SABL files for BO3. Was this planned at some point? If possible, will this be implemented at some point in the future?

**Comment by master131** [comment]
Never got around to implementing it, unlikely I will do it, but it's open-source for people to have a crack at it if they want. I would have thought the BO3 Mod Tools would provide some way to use custom sounds if that's what you are using the Sound Studio for.

**Comment by GillMart** [comment]
> Never got around to implementing it, unlikely I will do it, but it's open-source for people to have a crack at it if they want. I would have thought the BO3 Mod Tools would provide some way to use custom sounds if that's what you are using the Sound Studio for.

That's good to hear that it's open source. Will definitely look into more options, it's crazy that there isn't a tool that does custom sounds for BO3 as for as I know. Thanks for the info.
