### ISSUE TITLE
Saving is not supported for Black Ops 3 SABS/SABL files

### ISSUE THREAD

**Issue by tovaru** [master131/Black-Ops-II-Sound-Studio#9]
I know this is a current limitation, but do we have any insights on why this is not possible? I'd like to try fixing it.

**Comment by master131** [comment]
I haven't had time to implement it, if you want to feel free to.

**Comment by tovaru** [comment]
Thank you for your reply.
I just fixed it, the code is available on the fork I made. 
I only had to modify the WriteCalculatedDataAndStructures function.
